env:
    MANIFEST: https://github.com/crdroidandroid/android.git -b 11.0
    DEVICE: lavender
    OEM: xiaomi
    DT_LINK: https://github.com/mitmac29/device_xiaomi_lavender1.git -b 11
    DT_PATH: device/$OEM/$DEVICE
    VT_LINK: https://github.com/mitmac29/vendor_xiaomi_lavender1.git -b 11
    VT_PATH: vendor/$OEM/$DEVICE
    KT_LINK: https://github.com/mitmac29/kernel_xiaomi_lavender.git -b qti-oldcam
    PLATFORM: lavender
    KT_PATH: kernel/$OEM/lavender
    VP_LINK: https://github.com/mitmac29/packages_apps_ViPER4AndroidFX.git -b main
    VP_PATH: packages/apps/ViPER4AndroidFX
    CL_LINK: https://gitlab.com/sanjeevstunner/clang-r450784d.git
    CL_PATH: prebuilts/clang/host/linux-x86/clang-r450784d
    TARGET: bacon
    EXTRA_CMD: export SKIP_ABI_CHECKS=true
    LUNCH_COMBO: lineage_${DEVICE}-userdebug
    OUTPUT: crDroidAndroid*.zip

task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 240m  
  container:
      image: ghcr.io/sushrut1101/docker:arch
      cpu: 16
      memory: 32G



  Storage-Checker_script:
      - df -h
      - lsblk
      - ls -l -a -h
  
  Sync_script:
      - echo "============================"
      - echo "Syncing The Sources..."
      - echo "============================"
      - mkdir -p ~/work
      - cd ~/work
      - repo init --depth=1 -u $MANIFEST
      - repo sync -j4 --force-sync --no-tags --no-clone-bundle
      - git clone $DT_LINK $DT_PATH
      - git clone $VT_LINK $VT_PATH
      - git clone $KT_LINK $KT_PATH
      - git clone $VP_LINK $VP_PATH
      - git clone $CL_LINK $CL_PATH
      - echo "============================"
      - echo "Syncing Complete!"
      - echo "============================"

  Build_script:
      - echo "============================"
      - echo "Starting the Build..."
      - echo "============================"
      - cd ~/work
      - $EXTRA_CMD
      - export USE_CCACHE=1
      - export CCACHE_EXEC=/usr/bin/ccache
      - ccache -M 50G
      - . build/envsetup.sh
      - lunch "$LUNCH_COMBO"
      - mka -j31 $TARGET
     
  Upload_script:
      - echo "============================"
      - echo "Uploading the Build..."
      - echo "============================"
      - cd ~/work
      - cd out/target/product/"$DEVICE"
      - ls -lh
      - pwd
      - chmod 777 *
      - curl --upload-file $(echo $OUTPUT) https://transfer.sh | tee link.txt && echo " "
      - echo " "
      - echo "============================"
      - echo "Build Uploaded!"
      - echo "Please see the link Below-  "
      - echo "----------------------------"
      - cat link.txt && echo " "
      - echo "============================"
